source 'https://rubygems.org'
ruby '2.1.1'

gem 'rdiscount'
gem 'flickraw'
gem 'rack-rewrite'
gem 'sinatra'
gem 'haml'
gem 'rack'
gem 'syntax'
gem 'thin'
gem 'activerecord', '2.3.8'
gem 'builder'
gem 'capistrano'
gem 'sqlite3-ruby'
