# Blog meta-information
blog:
  title:  "Faded Pixels"       # Displayed as <title> on index page
  name:   "Faded Pixels"  # Displayed as part of <title> on article page
  author: "Brian Haberer"                # Used in feeds
  email:  "bhaberer@gmail.com"              # Used in feeds

# Admin credentials (prepend article URL with URL to see why)
admin:
  username: 'admin'
  password: 'phoenix'

# Set this relatively to application main ("marley") directory
data_directory: "../data"

# Set this to your own theme in "themes" directory
# theme: "{REPLACE WITH THEME NAME}"

# Google Analytics code ("UA-123132-00" etc)
ga_code: "UA-8105042-1"

# If you want to add synchronizing via Github post-receive hooks, insert some secure password here
# Then set a "Post-Receive URL" in Github administration to http://{YOUR SERVER}/sync?token={WHAT YOU SET BELOW}
github_token: ~

# See http://soakedandsoaped.com/articles/2006/10/01/how-to-protect-a-rails-application-against-spam-with-akismet
akismet: 
  key: "91d7a35c0598"
  url: "http://fadedpixels.net/"
